blueprint:
  name: My Example Blueprint
  description: Ein Beispiel-Blueprint für tgBlueprintMerger
  domain: automation
  input:
    #START-tgMerger=myBlueprintExample_input.yaml
    #END-tgMerger

trigger:
  #START-tgMerger=myBlueprintExample_trigger.yaml
  #END-tgMerger

condition:
  #START-tgMerger=myBlueprintExample_condition.yaml
  #END-tgMerger

action:
  - variables:
      message: >-
        {# START-tgMerger=myBlueprintExample_var_message.jinja #}
        {{- "Default message" -}}
        {#END-tgMerger#}
  - service: notify.persistent_notification
    data:
      message: "{{ message }}"
      title: "Blueprint Example"

