blueprint:
  name: &i18n:10001:My Example Blueprint&
  description: &i18n:10002:Ein Beispiel-Blueprint für tgBlueprintMerger&
  domain: automation
  input:
    #START-tgMerger=myBlueprintExample_input.yaml
    #END-tgMerger
#Doc-Start
#diese ist nur eine Doku die im Output herausgefiltert ist 
#Doc-End auch das wird entfernt
trigger:
  #START-tgMerger=myBlueprintExample_trigger.yaml
  #END-tgMerger

condition:
  #START-tgMerger=myBlueprintExample_condition.yaml
  #END-tgMerger

action:
  - variables:
      message: >-
        {# START-tgMerger=myBlueprintExample_var_message.jinja #}
        {{- "Default message" -}}
        {#END-tgMerger#}
  - service: notify.persistent_notification
    data:
      message: "{{ message }}"
      title: "Blueprint Example"

